[package]
name = "mmu"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.134"
serde = { version = "1.0.216", features = ["derive"] }
regex = "1.11.1"
reqwest = { version = "0.12.9", features = ["blocking", "json"] }
